language: cpp
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.5
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.5
    - libboost-dev
    - libedit-dev
    - libelf-dev
    - libxml2-dev
    - libxslt1-dev
    - llvm-3.5-dev
before_install:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.sh
  - chmod a+x cmake-3.3.1-Linux-x86_64.sh
  - ./cmake-3.3.1-Linux-x86_64.sh --skip-license --prefix=$HOME
compiler:
  - clang
script: CC=clang-3.5 CXX=clang++-3.5 $HOME/bin/cmake . && make -j2
sudo: false
